var express = require('express');
var jwt = require('express-jwt');
const authguard = require('../middleware/auth.js');
var router = express.Router();

const welcome = require('../welcome');
router.get('/', welcome);

const userModel = require('../Model/users');
router.post('/createuser', userModel.create);
router.post('/loginuser', userModel.loginUser);
router.post('/admincreateuser', userModel.admincreate);
router.route('/adminupdate').post(authguard, userModel.adminUpdate);
router.post('/adminloginuser', userModel.adminloginUser);
router.route('/getadminuser').post(authguard, userModel.getadminUser);
router.get('/getalladminuser/:_page/:_limit/:_sort/:_order', userModel.getalladminUser);
router.route('/deleteadminuser').post(authguard, userModel.deleteadminUser);
router.route('/deleteempuser').post(authguard, userModel.deleteempUser);
router.route('/getuserbilling').get(authguard, userModel.getuserBilling);
router.get('/getallcontractorlist/:_page/:_limit/:_sort/:_order', userModel.getallcontractorList);
router.route('/isuseractive').post(authguard, userModel.isuserActive);
router.route('/getallbillingamount').get(authguard, userModel.getallbillingAmount);
router.route('/getallpendingamountcnt').get(authguard, userModel.getallpendingAmountcnt);
router.route('/getallfacebookusercnt').get(authguard, userModel.getallFacebookusercnt);
router.route('/getallgoogleusercnt').get(authguard, userModel.getallGoogleusercnt);
router.route('/getallusercnt').get(authguard, userModel.getAllusercnt);
router.route('/globalsettingscreate').post(authguard, userModel.globalsettingsCreate);
router.route('/getglobalprice').get(authguard, userModel.getglobalprice);
router.route('/employerpriceupdate').post(authguard, userModel.employerpriceUpdate);
router.post('/activateuser', userModel.activateUser);
router.post('/otpcheck', userModel.otpCheck);
router.post('/resendotp', userModel.resendOTP);
router.post('/createusersso', userModel.createSSO);
router.route('/createemployer').post(authguard, userModel.createEmployer);
router.route('/deleteuser').post(authguard, userModel.deleteUser);
router.route('/getuser').post(authguard, userModel.getUser);
router.route('/updateaccounttype').post(authguard, userModel.updateAccounttype);
router.route('/updateaccountname').post(authguard, userModel.updateAccountname);
router.route('/updateemail').post(authguard, userModel.updateEmail);
router.post('/updateemailconfirmation', userModel.updateEmailconfirmation);
router.route('/updatepassword').post(authguard, userModel.updatePassword);
router.route('/adminupdatepassword').post(authguard, userModel.adminupdatePassword);
router.route('/updatephone').post(authguard, userModel.updatePhone);
router.route('/update2fa').post(authguard, userModel.update2FA);
router.post('/forgotpassword', userModel.forgotPassword);
router.post('/forgotpassconfirmation', userModel.forgetPasswordconfirmation);
router.post('/adminforgotpassword', userModel.adminforgotPassword);
router.post('/adminforgotpassconfirmation', userModel.adminforgetPasswordconfirmation);
router.route('/updatestripecard').post(authguard, userModel.updatestripeCard);
router.route('/creditpackagestripepayment').post(authguard, userModel.creditpackagestripePayment); 
router.route('/monthlybillingpayment').post(authguard, userModel.monthlybillingPayment);  
router.route('/retrievecarddetails').post(authguard, userModel.retrieveCarddetails);


const billing = require('../Model/billing');
router.route('/getcurmnthbillingamount').get(authguard, billing.getcurmnthbillingAmount);
router.get('/getalluserbilling/:_page/:_limit/:_sort/:_order', billing.getalluserBilling);

const dynamics = require('../Model/dynamics');
router.route('/countryseed').post(authguard, dynamics.countrySeed);
router.route('/languageseed').post(authguard, dynamics.languageSeed);
router.route('/jobtypeseed').post(authguard, dynamics.jobtypeSeed);
router.route('/jobscheduleseed').post(authguard, dynamics.jobscheduleSeed);
router.route('/supplementalpayseed').post(authguard, dynamics.supplementalpaySeed);
router.route('/benefitsofferedseed').post(authguard, dynamics.benefitsofferedSeed);
router.route('/getallcountry').get(authguard, dynamics.getallcountry);
router.route('/getallanguage').get(authguard, dynamics.getalllanguage);
router.route('/getalljobtype').get(authguard, dynamics.getalljobtype);
router.route('/getalljobschedule').get(authguard, dynamics.getalljobschedule);
router.route('/getallsupplementalpay').get(authguard, dynamics.getallsupplementalpay);
router.route('/getallbenefitsoffered').get(authguard, dynamics.getallbenefitsoffered);

const job = require('../Model/job');
router.route('/jobcategoryseed').post(authguard, job.jobcategorySeed);
router.route('/addjobcategory').post(authguard, job.addjobCategory);
router.route('/updatejobcategory').post(authguard, job.updatejobCategory);
router.route('/deletejobcategory').post(authguard, job.deletejobCategory);
router.route('/getalljobcategory').get(authguard, job.getalljobCategory);
router.route('/getjobcategory').post(authguard, job.getjobCategory);
router.route('/addjob').post(authguard, job.addJob);
router.route('/updatejob').post(authguard, job.updateJob);
router.route('/updatejobstatus').post(authguard, job.updateJobstatus);
router.route('/deletejob').post(authguard, job.deleteJob);
router.route('/getalljoblocation').get(authguard, job.getalljobLocation);
router.get('/getalljobs', job.getallJobs);
router.get('/getallfeedjobs', job.getallfeedJobs);
router.post('/getpublicjobs', job.getpublicJobs);
router.route('/getjob').post(authguard, job.getJob);
router.route('/searchjobstemplate').post(authguard, job.searchjobsTemplate);
router.post('/searchalljobs', job.searchallJobs);
router.post('/searchallfeedjobs', job.searchallfeedJobs);
router.post('/getalljobtitle', job.getallJobtitle);
router.post('/getalljobcompany', job.getallJobcompany);
router.route('/copyjob').post(authguard, job.copyJob);
router.route('/recentsearchjobs').post(authguard, job.recentsearchJobs);
router.route('/recentsearches').post(authguard, job.recentsearches);
router.post('/recentsearchespublic', job.recentsearchespublic);
router.post('/gblsearchjobs', job.gblsearchJobs);
router.route('/deleterecentsearchjobs').post(authguard, job.deleterecentsearchJobs);
router.route('/jobapply').post(authguard, job.jobApply);
router.route('/jobpurchaselimit').post(authguard, job.jobpurchaseLimit);
router.route('/getallpurchaselimit').post(authguard, job.getallPurchaseLimit);
router.route('/updatecreditflag').post(authguard, job.updatecreditFlag);
router.route('/getalljobszerocreditflag').get(authguard, job.getalljobszeroCreditflag);
router.route('/createconversation').post(authguard, job.createConversation);
router.route('/getallconversation').post(authguard, job.getallConversation);
router.route('/getconusersbyemp').post(authguard, job.getconusersbyEmp);
router.route('/getempusersbycon').post(authguard, job.getempusersbyCon);
router.post('/generatemonthlybilling', job.generateMonthlybilling);
router.route('/getbillinghistory').post(authguard, job.getBillingHistory);
router.route('/getcurmonbilling').post(authguard, job.getCurMonbilling); 
router.route('/gettodaybilling').post(authguard, job.getTodaybilling);
router.post('/deletejobfeedData',job.deletejobfeedData);


const predealquestions = require('../Model/predealquestions');
router.route('/predealcategoryseed').post(authguard, predealquestions.predealcategorySeed);
router.route('/addpredealcategory').post(authguard, predealquestions.addpredealCategory);
router.route('/updatepredealcategory').post(authguard, predealquestions.updatepredealCategory);
router.route('/deletepredealcategory').post(authguard, predealquestions.deletepredealCategory);
router.route('/getallpredealcategory').get(authguard, predealquestions.getallpredealCategory);
router.route('/getpredealcategory').post(authguard, predealquestions.getpredealCategory);
router.route('/addpredealquestions').post(authguard, predealquestions.addpredealQuestions);
router.route('/updatepredealquestions').post(authguard, predealquestions.updatepredealQuestions);
router.route('/deletepredealquestions').get(authguard, predealquestions.deletepredealQuestions);
router.route('/getpredealquestions').post(authguard, predealquestions.getpredealQuestions);
router.route('/getallpredealquestions').post(authguard, predealquestions.getallpredealQuestions);
router.route('/savepredealquestions').post(authguard, predealquestions.savepredealQuestions);
router.route('/addcustomjobdealquestions').post(authguard, predealquestions.addcustomjobdealQuestions);


const resume = require('../Model/resume');
router.route('/citystateseed').post(authguard, resume.citystateSeed);
router.route('/getallcitystate').post(authguard, resume.getallcityState);
router.route('/fieldofstudyseed').post(authguard, resume.fieldofstudySeed);
router.route('/getallfieldofstudy').post(authguard, resume.getallfieldofStudy);
router.route('/addnewsectionseed').get(authguard, resume.addnewsectionSeed);
router.route('/getalladdnewsection').get(authguard, resume.getalladdnewSection);
router.route('/listpredefinedskills').post(authguard, resume.listpredefinedSkills);
router.route('/createresume').post(authguard, resume.createResume);
router.route('/updateresume').post(authguard, resume.updateResume);
router.route('/deleteresume').post(authguard, resume.deleteResume);
router.route('/createeducation').post(authguard, resume.createEducation);
router.route('/updateeducation').post(authguard, resume.updateEducation);
router.route('/deleteeducation').post(authguard, resume.deleteEducation);
router.route('/createworkexperience').post(authguard, resume.createworkExperience);
router.route('/updateworkexperience').post(authguard, resume.updateworkExperience);
router.route('/deleteworkexperience').post(authguard, resume.deleteworkExperience);
router.route('/createcurricularactivities').post(authguard, resume.createcurricularActivities);
router.route('/updatecurricularactivities').post(authguard, resume.updatecurricularActivities);
router.route('/deletecurricularactivities').post(authguard, resume.deletecurricularActivities);
router.route('/createdesiredjob').post(authguard, resume.createdesiredJob);
router.route('/updatedesiredjob').post(authguard, resume.updatedesiredJob);
router.route('/deletedesiredjob').post(authguard, resume.deletedesiredJob);
router.route('/getdesiredjobbyuid').post(authguard, resume.getdesiredJobbyuid);
router.route('/isresumeprivate').post(authguard, resume.isresumePrivate);
router.route('/resumeheadline').post(authguard, resume.resumeHeadline);
router.route('/searchresumes').post(authguard, resume.searchResumes);

router.route('/getresume').post(authguard, resume.getResume);
router.route('/getresumesbyuser').post(authguard, resume.getResumesbyuser);
router.route('/getallresumes').post(authguard, resume.getallResumes);
router.route('/geteducation').post(authguard, resume.getEducation);
router.route('/getalleducation').post(authguard, resume.getallEducation);
router.route('/getworkexperience').post(authguard, resume.getworkExperience);
router.route('/getallworkexperience').post(authguard, resume.getallworkExperience);
router.route('/getcurricularactivities').post(authguard, resume.getcurricularActivities);
router.route('/getallcurricularactivities').post(authguard, resume.getallcurricularActivities);
router.route('/getdesiredjob').post(authguard, resume.getdesiredJob);

router.route('/getalldesiredjobtitle').post(authguard, resume.getalldesiredJobtitle);
router.route('/getallcompany').post(authguard, resume.getallCompany);
router.route('/getcounteducation').post(authguard, resume.getcountEducation);
router.route('/getallassessment').post(authguard, resume.getallAssessment);
router.route('/getallmilitary').post(authguard, resume.getallMilitary);
router.route('/getallworkexperiencecount').post(authguard, resume.getallworkExperiencecount);
router.route('/getalljobappliedbyuser').post(authguard, resume.getalljobappliedbyUser);
router.route('/getjobappliedbyuser').post(authguard, resume.getjobappliedbyUser);
router.route('/getalljobappliedtointerview').post(authguard, resume.getalljobappliedtoInterview);
router.route('/getalljobappliedtoarchived').post(authguard, resume.getalljobappliedtoArchived);
router.route('/updatejobappliedstatus').post(authguard, resume.updatejobappliedStatus);
router.route('/jobsavebyuser').post(authguard, resume.jobsavebyUser);
router.route('/getalljobsaved').post(authguard, resume.getalljobSaved);
router.route('/getjobsaved').post(authguard, resume.getjobSaved);
router.route('/deletejobsaved').post(authguard, resume.deletejobSaved);
router.route('/invitejobtoapply').post(authguard, resume.invitejobtoApply);
router.route('/getalljobinvited').post(authguard, resume.getalljobInvited);
router.route('/deletejobinvited').post(authguard, resume.deletejobInvited);
router.route('/getallrejected').post(authguard, resume.getallrejected);
router.route('/getalljobscountbyuser').post(authguard, resume.getalljobscountbyUser);
router.route('/getallinvitedjobscount').post(authguard, resume.getallInvitedjobscount);


router.get('/getjobfeeddata', job.getjobfeedData);

module.exports = router;